import { Nil } from '@src/types/global';

export type MutualProductDTO = {
  id: number;
  groupId: number;
  subGroupId: number;
  personId: number;
  personOneId: number;
  taxClassificationId?: number | Nil;
  onlineOrderId?: number | Nil;
  manufacturerCode?: string | Nil;
  dicCode?: string | Nil;
  geapCode?: string | Nil;
  unimedCode?: string | Nil;
  saoLucasCode?: string | Nil;
  susCode?: string | Nil;
  simproCode?: string | Nil;
  pathCode?: string | Nil;
  ipiCode?: string | Nil;
  operatorCode?: string | Nil;
  anvisaCode?: string | Nil;
  anpCode?: string | Nil;
  msRecordCode?: string | Nil;
  minQuantity?: number | Nil;
  maxQuantity?: number | Nil;
  cupomQuantity?: number | Nil;
  promotionQuantity?: number | Nil;
  validityDaysQuantity?: number | Nil;
  marginValue?: number | Nil;
  beforeMarginAValue?: number | Nil;
  beforeMarginVValue?: number | Nil;
  wholesaleMarginValue?: number | Nil;
  theoreticalMarginValue?: number | Nil;
  weightValue?: number | Nil;
  acquisitionCostValue?: number | Nil;
  averageCostValue?: number | Nil;
  singleCostValue?: number | Nil;
  fixedCostValue?: number | Nil;
  finalCostAValue?: number | Nil;
  finalCostVValue?: number | Nil;
  beforeFinalCostAValue?: number | Nil;
  beforeFinalCostVValue?: number | Nil;
  grossWeightValue?: number | Nil;
  ipiNumber?: number | Nil;
  icmsNumber?: number | Nil;
  icmsSubNumber?: number | Nil;
  shippingNumber?: number | Nil;
  reductionNumber?: number | Nil;
  othersTaxesNumber?: number | Nil;
  markupANumber?: number | Nil;
  markupVNumber?: number | Nil;
  beforeMarkupANumber?: number | Nil;
  beforeMarkupVNumber?: number | Nil;
  concurrentOneNumber?: number | Nil;
  concurrentTwoNumber?: number | Nil;
  icmsYieldNumber?: number | Nil;
  packingDescription?: string | Nil;
  referenceDescription?: string | Nil;
  pisCofinsDescription?: string | Nil;
  mercosurDescription?: string | Nil;
  specificationDescription?: string | Nil;
  productNoteDescription?: string | Nil;
  promotionDescription?: string | Nil;
  retailPromotionDescription?: string | Nil;
  ipptDescription?: string | Nil;
  ipiSituationDescription?: string | Nil;
  cfopDDescription?: string | Nil;
  cfopFDescription?: string | Nil;
  cfopEntDDescription?: string | Nil;
  cfopEntFDescription?: string | Nil;
  isIcmsFightPoverty: boolean;
  isAssortedWeight: boolean;
  noCreditIcmsPurchase: boolean | Nil;
  commandPrinter: string;
  mvast: number;
  mvastret: number;
  mvastFlag?: string | Nil;
  distred?: number | Nil;
  name: string;
  type?: string | Nil;
  itemType?: string | Nil;
  compositionType?: number | Nil;
  indMed?: string | Nil;
  cean?: string | Nil;
  unit: string;
  hideBatch: number;
  purchasePrice?: number | Nil;
  purchaseFactor?: string | Nil;
  maxConsumerPrice?: number | Nil;
  beforePurchasePrice?: number | Nil;
  purchaseDate?: Date | Nil;
  createdDate?: Date | Nil;
};
